### ISSUE TITLE
some solutions for any language clients call the endpoints of each other? 

### ISSUE THREAD

**Issue by printfcoder** [micro/clients#1]

**Comment by asim** [comment]
What should be the design here?

**Comment by printfcoder** [comment]
client {
  Register(...)  // to micro bridge
  GetService(...) // calls micro bridge for getting addr of the service
  cache() // caches the addr (private func)
  Call(ip:port, args...) //
  Handle(...)  // tcp or http or ...
}

so we need `micro bridge` which likes `micro proxy` in the past version.

**Comment by asim** [comment]
I'm not sure that's how we'll structure it.

The micro proxy will act as an the fixed entry point that deals with gRPC. We then have a service equivalent of every go-micro interface or thereabouts which will have code generated clients.

```
clients/
    proto/
        registry/
        broker/
        ...
```

```
grpc call registry => micro proxy => registry service
```

**Comment by printfcoder** [comment]
yea, code generated clients save so many things. Communications of `Registry`, `Call`, `Handle` can be integrated into those codes.

`Registry` and `Selector` call micro proxy to register and select services.

`Call` calls the target service

`Handler` handles all requests from any `Call`

and How do `Broker` , `Subscribe`, and `Publish` work? import special broker package or base on micro proxy?

Importing package means we need to implement all features of the Broker. if not, using micro proxy will make it very heavy and to be the bottleneck of the running system.

**Comment by asim** [comment]
We now have clients that let you call through a client api. Still figuring out the best way to surface this
